### ISSUE TITLE
关于二维码无法显示的问题，怎样解决？

### ISSUE THREAD

**Issue by anyi2** [asiacny/zero-width-qrcode-sqlite-shortener#1]
用的 apache ，无法实现 Nginx 的伪静态。求解。多谢。

如图。
![image](https://user-images.githubusercontent.com/40451747/68604988-9363c580-04e6-11ea-869a-abfbdd35c03c.png)

**Comment by anyi2** [comment]
重新安装 Nginx 发现问题并未能解决。

**Comment by asiacny** [comment]
刚开你这网站，很正常啊，另外那个config.php中的网址最后不要加斜杠
二维码生成库是第三方的，很老了，在较新的php中会报错，php.ini关闭错误回显就行display_errors = Off

**Comment by anyi2** [comment]
> 刚开你这网站，很正常啊，另外那个config.php中的网址最后不要加斜杠
> 二维码生成库是第三方的，很老了，在较新的php中会报错，php.ini关闭错误回显就行display_errors =关

感谢，已解决。
背景可以更换成为 BING的每日一图嘛？

**Comment by asiacny** [comment]
不客气，建议不错，周末有时间研究研究
